# Generated by Django 5.2.11 on 2026-02-18 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("ENDED", "Ended"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("daily_budget_cents", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RawAdEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField()),
                ("event_time", models.DateTimeField()),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("tenant_id", models.BigIntegerField()),
                ("user_id", models.CharField(max_length=255)),
                ("session_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(max_length=32)),
                ("campaign_id", models.BigIntegerField(default=0)),
                ("line_item_id", models.BigIntegerField(default=0)),
                ("placement_id", models.BigIntegerField(default=0)),
                ("creative_id", models.BigIntegerField(default=0)),
                ("value_cents", models.BigIntegerField(default=0)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="LineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bid_cents", models.IntegerField(default=1)),
                ("targeting_json", models.JSONField(blank=True, default=dict)),
                ("pacing_mode", models.CharField(default="STANDARD", max_length=32)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ads_platform.campaign",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ads_platform.placement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Creative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_sku", models.CharField(max_length=128)),
                ("image_url", models.URLField()),
                ("landing_url", models.URLField()),
                (
                    "line_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creatives",
                        to="ads_platform.lineitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MinuteAdAggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minute", models.DateTimeField()),
                ("tenant_id", models.BigIntegerField()),
                ("campaign_id", models.BigIntegerField(default=0)),
                ("placement_id", models.BigIntegerField(default=0)),
                ("impressions", models.BigIntegerField(default=0)),
                ("clicks", models.BigIntegerField(default=0)),
                ("conversions", models.BigIntegerField(default=0)),
                ("revenue_cents", models.BigIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("minute", "tenant_id", "campaign_id", "placement_id"),
                        name="uniq_minute_tenant_campaign_placement",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="placement",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ads_platform.tenant"
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ads_platform.tenant"
            ),
        ),
        migrations.CreateModel(
            name="AttributionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("click_window_hours", models.IntegerField(default=24)),
                ("view_window_hours", models.IntegerField(default=24)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ads_platform.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.UniqueConstraint(
                fields=("tenant", "key"), name="uniq_tenant_placement"
            ),
        ),
    ]
